services:
  - type: web
    name: rfi-bot
    env: docker
    repo: https://github.com/wmehaisi/rfi_bot
    plan: free
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: BOT_TOKEN
        sync: false
